/* a) */
SELECT (SELECT MAX(SALAR) FROM TEMPLE), NUMDE
FROM TEMPLE;

/* b) */
SELECT NUMDE
FROM TEMPLE
WHERE SALAR > (SELECT AVG(SALAR)FROM TEMPLE);

/* c) */
SELECT NUMDE, MAX(SALAR)
FROM TEMPLE
GROUP BY NUMDE;

/* d) */
SELECT NUMDE
FROM TEMPLE
GROUP BY NUMDE HAVING
    AVG(SALAR) > (SELECT AVG(SALAR) FROM TEMPLE);

/* TIENE VALORES NULL PERO NO HACE FALTA COALESCE */
SELECT MAX(COMIS)
FROM TEMPLE;

/* NUM EMPLE EN 112 Y 121*/
SELECT NUMDE, COUNT(*)
FROM TEMPLE
WHERE NUMDE IN(112, 121)
GROUP BY NUMDE
ORDER BY 1;

/**/
SELECT NUMHI, MAX(SALAR), MIN(SALAR)
FROM TEMPLE
GROUP BY NUMHI HAVING MAX(SALAR) > 2000
ORDER BY 1;

/**/
SELECT NUMHI, MAX(SALAR), MIN(SALAR) FROM TEMPLE WHERE SALAR>800
GROUP BY NUMHI
HAVING COUNT(*)>2 AND MAX(SALAR)>2000
ORDER BY NUMHI;

SELECT NUMHI, MAX(SALAR), MIN(SALAR)
FROM TEMPLE
WHERE SALAR > 800
GROUP BY NUMHI
HAVING COUNT(*) > 2 AND MAX(SALAR) > 2000
ORDER BY NUMHI;

/* 2 */
SELECT NUMDE, SALAR
FROM TEMPLE
WHERE SALAR >= 0.6 * (SELECT MAX(SALAR) FROM TEMPLE)
ORDER BY NUMDE;

/* 4 */
SELECT COUNT(*), COUNT(EXTEL)
FROM TEMPLE
WHERE NUMDE = 112;

/* 5 */
SELECT COUNT(*), COUNT(COMIS), SUM(COMIS), AVG(COMIS)
FROM TEMPLE
WHERE NUMDE = 112;

/* 6 */
SELECT COUNT(DISTINCT COMIS), AVG(COMIS)
FROM TEMPLE
WHERE COMIS IS NOT NULL;

/* 7 */
SELECT AVG(NUMHI) FROM TEMPLE
WHERE NUMDE = 122;

/* 8 */
SELECT NUMDE, PRESU, (SELECT(AVG(PRESU)) FROM TDEPTO)
FROM TDEPTO
WHERE DEPDE = 100;

/* 13 */
SELECT (SUM(SALAR) + SUM(COMIS) * 14)
FROM TEMPLE;

