SELECT NOMEM
FROM TEMPLE
WHERE SALAR >= (SELECT SALAR*1.5
                FROM TEMPLE
                WHERE NOMEM = 'FIERRO, CLAUDIA')
ORDER BY NOMEM;

SELECT NOMDE
FROM TDEPTO
WHERE DEPDE IS NULL
ORDER BY NOMDE;

SELECT NOMEM FROM TEMPLE
WHERE SALAR > SOME(SELECT SALAR
                FROM TEMPLE
                WHERE NUMDE = 122)
ORDER BY NOMEM;

SELECT NOMEM FROM TEMPLE
WHERE SALAR > SOME(SELECT SALAR*3.5
                FROM TEMPLE
                WHERE NUMDE = 122)
ORDER BY NOMEM;

/*  */
SELECT NOMEM FROM TEMPLE
WHERE SALAR BETWEEN 2500 AND 3000
ORDER BY NOMEM;

/* MORA 1 */
SELECT NOMEM FROM TEMPLE
WHERE NOMEM LIKE 'MORA%'
ORDER BY NOMEM;

/* MORA 2 */
SELECT NOMEM FROM TEMPLE
WHERE NOMEM LIKE '%, VALERIANA%'
ORDER BY NOMEM;

/* EXTEL */
SELECT NOMEM FROM TEMPLE
WHERE EXTEL IN(250,750)
ORDER BY NOMEM;

/* MISMO DEPTO */
SELECT NOMEM, NUMDE 
FROM TEMPLE
WHERE NUMDE IN(SELECT NUMDE FROM TEMPLE
                WHERE NOMEM IN('ALBA, ADRIANA', 'FLOR, DOROTEA'))
ORDER BY 1;

/* ATOCHA 1 */
SELECT NOMCE, SEÑAS
FROM TCENTR
WHERE EXISTS(SELECT *
            FROM TCENTR
            WHERE SEÑAS LIKE '%ATOCHA%');
            

/*  */
SELECT NOMEM, COMIS
FROM TEMPLE
WHERE NUMDE = 110 AND EXISTS(SELECT *
FROM TEMPLE
WHERE NUMDE = 110 AND COMIS IS NOT NULL);

/* PRUEBA ANTA */
SELECT NOMEM, COMIS
FROM TEMPLE
WHERE NUMDE = 110 AND COMIS IS NOT NULL;

/**/
SELECT NUMDE, PRESU, (SELECT NUMDE FROM TDEPTO WHERE NUMDE = 112), (SELECT PRESU FROM TDEPTO WHERE NUMDE = 112)
FROM TDEPTO
WHERE NUMDE = 111;