/* TEMA 2 */

/* EJ PAG 7 */
SELECT NOMEM
FROM TEMPLE
WHERE SALAR >= (SELECT SALAR*1.5
                FROM TEMPLE
                WHERE NOMEM = 'FIERRO, CLAUDIA')
ORDER BY NOMEM;

/* EJ PAG 10 */
SELECT NOMDE
FROM TDEPTO
WHERE DEPDE IS NULL
ORDER BY NOMDE;

/* EJ PAG 11 */
SELECT NOMEM FROM TEMPLE
WHERE SALAR > ALL(SELECT SALAR
                FROM TEMPLE
                WHERE NUMDE = 122)
ORDER BY NOMEM;

/* EJ PAG 15 */
SELECT NOMEM FROM TEMPLE
WHERE SALAR > SOME(SELECT SALAR*3.5
                FROM TEMPLE
                WHERE NUMDE = 122)
ORDER BY NOMEM;

/* EJ PAG 18 */
SELECT NOMEM FROM TEMPLE
WHERE SALAR BETWEEN 2500 AND 3000
ORDER BY NOMEM;

/* EJ1 PAG 20 */
SELECT NOMEM FROM TEMPLE
WHERE NOMEM LIKE 'MORA%'
ORDER BY NOMEM;

/* EJ2 PAG 20 */
SELECT NOMEM FROM TEMPLE
WHERE NOMEM LIKE '%, VALERIANA%'
ORDER BY NOMEM;

/* EJ PAG 21 */
SELECT NOMEM FROM TEMPLE
WHERE EXTEL IN(250,750)
ORDER BY NOMEM;

/* EJ PAG 24 */
SELECT NOMEM, NUMDE 
FROM TEMPLE
WHERE NUMDE IN(SELECT NUMDE FROM TEMPLE
                WHERE NOMEM IN('ALBA, ADRIANA', 'FLOR, DOROTEA'))
ORDER BY 1;

/* EJ PAG 25 */
SELECT NOMCE, SEÑAS
FROM TCENTR
WHERE EXISTS(SELECT *
              FROM TCENTR
              WHERE SEÑAS LIKE '%ATOCHA%');

/* EJ PAG 27 */
SELECT NOMEM, COMIS
FROM TEMPLE
WHERE NUMDE = 110 AND EXISTS(SELECT *
                              FROM TEMPLE
                              WHERE NUMDE = 110 AND COMIS IS NOT NULL);

/* PRUEBA ANTA */
SELECT NOMEM, COMIS
FROM TEMPLE
WHERE NUMDE = 110 AND COMIS IS NOT NULL;

/* BOLETIN 2 - EJ2 */
SELECT NUMDE, PRESU, (SELECT NUMDE FROM TDEPTO WHERE NUMDE = 112), (SELECT PRESU FROM TDEPTO WHERE NUMDE = 112)
FROM TDEPTO
WHERE NUMDE = 111;
