/* BOLETIN 4 */

/* EJ */
SELECT NUMEM, NOMDE, E.NUMDE
FROM TEMPLE E, TDEPTO D
WHERE E.NUMDE = D.NUMDE;

/* 1 */
SELECT D.NOMDE, C.NOMCE
FROM TDEPTO D, TCENTR C
WHERE D.PRESU < 100 AND D.NUMCE = C.NUMCE
ORDER BY 1;

/* 2 */
SELECT MAX(SALAR)
FROM TEMPLE E, TDEPTO D
WHERE E.NUMDE = D.NUMDE AND D.NOMDE = 'FINANZAS';

/* 3 */
SELECT SALAR, NUMEM, NOMDE
FROM TEMPLE E, TDEPTO D
WHERE E.NUMDE = D.NUMDE AND SALAR >= 0.6*(SELECT MAX(SALAR) FROM TEMPLE)
ORDER BY 2;

/* 5 */
SELECT AVG(NUMHI)
FROM TEMPLE E, TDEPTO D
WHERE E.NUMDE = D.NUMDE AND NOMDE = 'PROCESO DE DATOS';

/* 6 */
SELECT NUMDE, PRESU, (SELECT AVG(PRESU) FROM TEMPLE) AS AVG
FROM TDEPTO
WHERE DEPDE = (SELECT NUMDE FROM TDEPTO WHERE NOMDE = 'DIRECCION COMERCIAL');

/* 9 */
SELECT NOMEM
FROM TEMPLE
WHERE EXISTS (SELECT * FROM TDEPTO D, TCENTR C
                WHERE D.NUMDE = 122 AND D.NUMCE = C.NUMCE AND C.SEÑAS LIKE '%ALCALA%') 
    AND NUMDE = 122 AND SALAR <= (SELECT AVG(SALAR) FROM TEMPLE WHERE NUMDE = 122)
ORDER BY 1;