/* BOLETIN 1 */

/* 1 */
SELECT NOMEM, NUMDE
FROM TEMPLE
WHERE NUMDE = 121;

/* 2 */
SELECT *
FROM TDEPTO
WHERE NUMDE = 121;

/* 3 */
SELECT NOMEM, SALAR
FROM TEMPLE
WHERE NUMHI > 3
ORDER BY 1;

/* 4 */
SELECT COMIS, NUMDE, NOMEM
FROM TEMPLE
WHERE SALAR < 1900
ORDER BY 2, 1 DESC;

/* 5 */
SELECT COMIS AS COMISION, NUMDE AS DEPTO, NOMEM AS EMPLEADO
FROM TEMPLE
WHERE SALAR < 1900
ORDER BY 2, 1 DESC;

/* 6 */
SELECT NOMDE
FROM TDEPTO
WHERE PRESU > 20
ORDER BY 1;

/* 7 */
SELECT DISTINCT NUMDE
FROM TEMPLE
WHERE SALAR < 2500;

/* 8 */
SELECT DISTINCT COMIS
FROM TEMPLE
WHERE NUMDE = 110;

/* 9 */
SELECT SALAR, COMIS
FROM TEMPLE
WHERE NUMDE = 111
ORDER BY 1 DESC, 2 DESC;

/* 10 */
SELECT NOMEM, SALAR, COMIS
FROM TEMPLE
WHERE COMIS >= 0.5*SALAR
ORDER BY 1;

/* 11 */
SELECT NOMEM, SALAR+30*(NUMHI-3) AS NEW
FROM TEMPLE
WHERE NUMHI >= 4
ORDER BY 1;

/* 12 */
SELECT CONCAT('Departamento de ', NOMDE) AS NAME, PRESU
FROM TDEPTO
WHERE PRESU < 30
ORDER BY 1;

/* 13 */
SELECT NOMDE, (PRESU + 3 * (PRESU/12) * 0.1) AS NEW
FROM TDEPTO
WHERE (PRESU/12*9) < 3000
ORDER BY 1;

/* 14 */
SELECT NOMEM, SALAR*12 AS ACTUAL, (SALAR*1.06*12) AS YEAR1, (SALAR*1.06*1.06*12) AS 
YEAR2, (SALAR*1.06*1.06*1.06*12) AS YEAR3
FROM TEMPLE
WHERE NUMHI > 4
ORDER BY 1;

/* 15 */
SELECT NOMEM
FROM TEMPLE
WHERE NUMHI*60 < SALAR*0.1
ORDER BY 1;

/* 16 */
SELECT NOMEM, (SALAR + COALESCE(COMIS, 0)) AS SALAR_TOTAL
FROM TEMPLE
WHERE NUMDE = 112
ORDER BY 2 DESC, NOMEM;

/* 17 */
SELECT NOMEM, (SALAR + COALESCE(COMIS, 0)) AS SALAR_TOTAL
FROM TEMPLE
WHERE SALAR > 1800
ORDER BY NUMEM;

/* 18 */
SELECT DISTINCT NUMDE
FROM TEMPLE
WHERE SALAR*0.2 < COMIS
ORDER BY 1;
