/* BOLETIN 3 */

/* 1 */
    SELECT MAX(SALAR)
    FROM TEMPLE
    WHERE NUMDE = 100;
    
    /* OPC 2*/
    SELECT NUMDE, MAX(SALAR)
    FROM TEMPLE
    GROUP BY NUMDE HAVING NUMDE = 100;
    
/* 2 */
SELECT SALAR, NOMEM
FROM TEMPLE
WHERE SALAR > 0.6*(SELECT MAX(SALAR) FROM TEMPLE)
ORDER BY 2;

/* 3 */
SELECT COUNT(*)
FROM TEMPLE;

/* 4 */
SELECT COUNT(*) AS NUM_EM, COUNT(DISTINCT EXTEL) AS NUM_EXTEL
FROM TEMPLE
WHERE NUMDE = 112;

/* 5 */
SELECT COUNT(*) AS NUM_EM, COUNT(COMIS) AS NUM_COMIS, SUM(COMIS), ROUND(AVG(COMIS), 2) AS MEDIA
FROM TEMPLE
WHERE NUMDE = 112;

/* 6 */
SELECT COUNT(DISTINCT COMIS) AS DIFF_COMIS, ROUND(AVG(COMIS), 2) AS MEDIA
FROM TEMPLE;

/* 7 */
SELECT AVG(NUMHI)
FROM TEMPLE
WHERE NUMDE = 122;

/* 8 */
SELECT NUMDE, PRESU, (SELECT AVG(PRESU) FROM TDEPTO) AS MEDIA_PRESU
FROM TDEPTO
WHERE NUMDE = 110;

/* 9 */
SELECT NOMEM
FROM TEMPLE
WHERE SALAR >= 3.5*(SELECT MIN(SALAR) FROM TEMPLE WHERE NUMDE = 123)
ORDER BY 1;

/* 10 */
SELECT COUNT(DISTINCT NUMDE), AVG(PRESU)
FROM TDEPTO;

/* 11 */
SELECT COUNT(DISTINCT NUMDE), AVG(PRESU)
FROM TDEPTO
WHERE TIDIR<>'P';

/* 12 */
SELECT NOMEM, (SALAR + COALESCE(COMIS, 0)) AS TOTAL
FROM TEMPLE
WHERE (SALAR + COALESCE(COMIS, 0)) = 3000 + (SELECT MIN(SALAR) FROM TEMPLE)
ORDER BY NUMDE;

/* 13 */
SELECT (SUM(SALAR)+SUM(COMIS))*14 FROM TEMPLE;

/* 14 */
SELECT AVG(SALAR)
FROM TEMPLE
WHERE SALAR <= 1.2*(SELECT MIN(SALAR) FROM TEMPLE WHERE NUMHI<>0 AND SALAR/NUMHI > 1000);

/* 16 */
SELECT AVG(PRESU)
FROM TDEPTO
WHERE PRESU > (SELECT AVG(PRESU) FROM TDEPTO);

/* 17 */
SELECT AVG(NUMHI)
FROM TEMPLE
WHERE NUMHI >=2;

/* 18 */
SELECT COUNT(*) AS NUM_EM
FROM TEMPLE
WHERE NUMDE IN(100,110);

/* 19 */
SELECT NUMDE, NUMHI, COUNT(*)
FROM TEMPLE
WHERE NUMDE IN(100,110)
GROUP BY NUMDE, NUMHI
ORDER BY 3;

/* 20 */
SELECT NUMDE, COUNT(*), SUM(SALAR), SUM(COMIS), SUM(NUMHI)
FROM TEMPLE 
GROUP BY NUMDE HAVING MAX(SALAR) > 4000
ORDER BY 1;

/* OPC 2 */
SELECT NUMDE, COUNT(*), SUM(SALAR), SUM(COMIS), SUM(NUMHI)
FROM TEMPLE
WHERE NUMDE IN (SELECT DISTINCT NUMDE FROM TEMPLE WHERE SALAR > 4000)
GROUP BY NUMDE
ORDER BY 1;

/* 21 */
SELECT NUMHI, ROUND(AVG(SALAR + COALESCE(COMIS, 0))/NUMHI,2) AS TOTAL
FROM TEMPLE
WHERE NUMHI <>0
GROUP BY NUMHI;

/* 22 */
SELECT NUMDE, ROUND(AVG(COMIS), 2) AS MEDIA_COMIS_DEPTO, 
    ROUND(SUM(COMIS)/COUNT(*), 2) AS MEDIA_TOTAL
FROM TEMPLE
GROUP BY NUMDE
ORDER BY 1;

/* 23 */
SELECT EXTEL, COUNT(*), ROUND(AVG(SALAR), 2) AS MEDIA
FROM TEMPLE
GROUP BY EXTEL;

/* 24 */
SELECT EXTEL, NUMDE, COUNT(*), ROUND(AVG(SALAR), 2) AS MEDIA
FROM TEMPLE
GROUP BY EXTEL, NUMDE
ORDER BY 1, 2;

/* 33 */
SELECT TIDIR, ROUND(AVG(PRESU), 2) AS AVG
FROM TDEPTO
GROUP BY TIDIR, NUMCE
ORDER BY 1;

/* 34 */
SELECT EXTEL
FROM TEMPLE
WHERE NUMDE IN (SELECT NUMDE FROM TEMPLE
                GROUP BY NUMDE HAVING COUNT(DISTINCT EXTEL) > 2)
GROUP BY EXTEL HAVING COUNT(*) BETWEEN 2 AND 4
ORDER BY 1;