/* BOLETIN 2 */

/* 2 */
SELECT NOMDE AS DEPTO_111, PRESU AS PRESU_111, 
(SELECT NOMDE FROM TDEPTO WHERE NUMDE=112) AS DEPTO_112, 
(SELECT PRESU FROM TDEPTO WHERE NUMDE=112) AS PRESU_112 FROM TDEPTO
WHERE NUMDE=111;

/* 3 */
SELECT NOMDE
FROM TDEPTO
WHERE DEPDE IS NULL;

/* 7 */
SELECT NOMEM
FROM TEMPLE 
WHERE SALAR > SOME(SELECT 3.5*SALAR
                    FROM TEMPLE
                    WHERE NUMDE = 123)
ORDER BY 1;


/* 8 */
    /* OPCION 1 */
    SELECT NOMEM, SALAR
    FROM TEMPLE
    WHERE SALAR = SOME(SELECT COMIS FROM TEMPLE)
    ORDER BY 1;
    
    /* OPCION 2 */
    SELECT NOMEM, SALAR
    FROM TEMPLE
    WHERE SALAR IN (SELECT COMIS FROM TEMPLE)
    ORDER BY 1;

/* 9 */
    /* OPCION 1 */
    SELECT NOMEM, SALAR
    FROM TEMPLE
    WHERE SALAR < SOME(SELECT (COMIS) FROM TEMPLE)
    ORDER BY 1;
    
    /* OPCION 2 */
    SELECT NOMEM, SALAR
    FROM TEMPLE
    WHERE SALAR < (SELECT MAX(COMIS) FROM TEMPLE)
    ORDER BY 1;
  
/* 10. Obtener por orden alfabético los nombres y 
salarios de los empleados cuyo salario es inferior 
al cuádruplo de la comisión más baja existente. */
SELECT NOMEM, SALAR
FROM TEMPLE
WHERE SALAR < 4*(SELECT MIN(COMIS) FROM TEMPLE)
ORDER BY 1;

/* sol del tipo */
SELECT NOMEM, SALAR
FROM TEMPLE
WHERE SALAR < ALL(SELECT 4*(COMIS) FROM TEMPLE WHERE COMIS  IS NOT NULL)
ORDER BY 1;

/* 12 */
SELECT NOMEM, SALAR
FROM TEMPLE
WHERE NUMHI > 0 AND SALAR/NUMHI NOT BETWEEN 1200 AND 2*COALESCE(COMIS,0)
ORDER BY 1;

/* 13 */
SELECT NOMEM
FROM TEMPLE
WHERE NOMEM LIKE 'MORA%, %'
ORDER BY 1;

/* 14 */
SELECT NOMEM
FROM TEMPLE
WHERE NOMEM LIKE '%, VALERIANA';

/* 15 */
SELECT NOMEM
FROM TEMPLE
WHERE NOMEM LIKE '_______, %';

/* 16 */
SELECT NOMEM
FROM TEMPLE
WHERE NOMEM LIKE '______%, %'
ORDER BY 1;

/* 17 */
SELECT NOMEM
FROM TEMPLE
WHERE NOMEM NOT LIKE '____%, %';

/* 18 */
SELECT NOMEM
FROM TEMPLE
WHERE NOMEM LIKE '%EZ, %_O';

/* 19 */
SELECT NOMEM, SALAR*0.01 AS REGALO
FROM TEMPLE
WHERE NOMEM LIKE '%, %HONORI%';


/* 20 */
    SELECT NOMEM
    FROM TEMPLE
    WHERE NUMDE = (SELECT DISTINCT NUMDE FROM TEMPLE
                    WHERE NOMEM = 'GALVEZ, PILAR') OR NUMDE = (SELECT NUMDE FROM TEMPLE
                    WHERE NOMEM = 'FLOR, DOROTEA')
    ORDER BY 1;
    
    /* BETTER OPTION */
    SELECT NOMEM
    FROM TEMPLE
    WHERE NUMDE IN (SELECT NUMDE FROM TEMPLE 
                    WHERE NOMEM IN ('GALVEZ, PILAR', 'FLOR, DOROTEA'))
    ORDER BY 1;

/* 23 */
SELECT NOMEM, SALAR
FROM TEMPLE
WHERE NUMDE = 111 AND COMIS IS NOT NULL 
    AND EXISTS (SELECT * FROM TEMPLE
                WHERE NUMDE=111 AND COMIS IS NOT NULL AND COMIS>0.15*SALAR)               
ORDER BY 1;

/* 24 */
SELECT NOMEM, COMIS
FROM TEMPLE
WHERE NUMDE = 110 AND EXISTS (SELECT * FROM TEMPLE 
                                WHERE NUMDE = 110 AND COMIS IS NOT NULL)
ORDER BY 1;

/* 25 */
SELECT NOMEM, SALAR, FECIN
FROM TEMPLE
WHERE FECIN > '1.1.1988' OR SALAR < 2000
ORDER BY 1, 2 DESC;

/* 27 */
SELECT NOMEM, SALAR, NUMHI
FROM TEMPLE
WHERE (NUMHI = 0 AND SALAR > 2000) OR (NUMHI > 0 AND SALAR < 3000)
ORDER BY 1;

/* 28 */
SELECT NOMEM, SALAR
FROM TEMPLE
WHERE (NUMDE IN(110,111)) AND (NUMHI = 0 OR SALAR/NUMHI>1000)
AND EXISTS (SELECT * FROM TEMPLE WHERE COMIS IS NULL AND NUMDE IN (111,112));

/* 29 */
SELECT NOMDE
FROM TDEPTO
WHERE DEPDE IS NULL OR TIDIR = 'F' OR (TIDIR = 'P' AND PRESU < 50)
ORDER BY 1;


